# Generated by Django 4.1.3 on 2022-11-13 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrep', models.CharField(max_length=200, null=True)),
                ('tipo', models.CharField(choices=[('H', 'Heladeria'), ('PZ', 'Pizzeria'), ('CR', 'Comida Rapida'), ('B', 'Bebidas')], default='H', max_length=20)),
                ('precio', models.FloatField(blank=True)),
                ('Estado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('C', 'Cliente'), ('A', 'Asesor')], default='C', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
