# Generated by Django 4.1.3 on 2022-11-13 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_estado_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
