# Generated by Django 4.1.3 on 2022-11-13 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usuarios_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='creacion',
            new_name='created',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
