# Generated by Django 4.1.3 on 2022-11-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_pedido_id_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_ped',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
